/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.jlangford.xnfce;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  default font size 
         */
        public static final int defaultFont=0x7f050000;
    }
    public static final class drawable {
        public static final int file=0x7f020000;
        public static final int folder=0x7f020001;
        public static final int logo=0x7f020002;
    }
    public static final class id {
        public static final int btnGo=0x7f070001;
        public static final int btnToEncrypt=0x7f070007;
        public static final int fileImg=0x7f070002;
        public static final int fileName=0x7f070003;
        public static final int filePath=0x7f070000;
        public static final int filePickerList=0x7f070006;
        public static final int fileSize=0x7f070004;
        public static final int myToDecrypt=0x7f070008;
        public static final int upDirectory=0x7f070005;
    }
    public static final class layout {
        public static final int encryptfile=0x7f040000;
        public static final int filelistitem=0x7f040001;
        public static final int filepicker=0x7f040002;
        public static final int main=0x7f040003;
    }
    public static final class mipmap {
        public static final int icon=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f060001;
        public static final int btnDecrypt=0x7f060003;
        /**  Strings for buttons 
         */
        public static final int btnEncrypt=0x7f060002;
        public static final int btnGo=0x7f060005;
        public static final int btnParent=0x7f060004;
        public static final int hello=0x7f060000;
        /**  Strings for labels 
         */
        public static final int lblFile=0x7f060006;
        public static final int rdioAES=0x7f060008;
        /**  Strings for radio buttons 
         */
        public static final int rdioDES=0x7f060007;
    }
}
