#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xNFCE.Resource", IsApplication=true)]

namespace xNFCE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int defaultFont = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int file = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int folder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_file = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_folder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int FilePickerList = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int btnGo = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int btnToDecrypt = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int btnToEncrypt = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int decryptBtnGo = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int decryptFilePath = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int decryptPassword = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int decryptUsePassword = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int fileImg = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int fileName = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int filePath = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int filePickerList = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int fileSize = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int password = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int upDirectory = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int usePassword = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DecryptFile = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int EncryptFile = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int FileListItem = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int FilePicker = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int FilePickerFragment = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int btnDecrypt = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btnEncrypt = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int btnGo = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int btnParent = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int lblFile = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int rdioAES = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int rdioDES = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
